---
title: "CodeBook"
author: "alexmtorroella"
date: "May 24, 2015"
output: html_document
---

### From the features description of the "Human Activity Recognition Using Smart Phones" data set

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ  
tGravityAcc-XYZ  
tBodyAccJerk-XYZ  
tBodyGyro-XYZ  
tBodyGyroJerk-XYZ  
tBodyAccMag  
tGravityAccMag  
tBodyAccJerkMag  
tBodyGyroMag  
tBodyGyroJerkMag  
fBodyAcc-XYZ  
fBodyAccJerk-XYZ  
fBodyGyro-XYZ  
fBodyAccMag  
fBodyAccJerkMag  
fBodyGyroMag  
fBodyGyroJerkMag  

The set of variables that were estimated from these signals are: 

mean(): Mean value
std(): Standard deviation

[...]

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravityMean  
tBodyAccMean  
tBodyAccJerkMean  
tBodyGyroMean  
tBodyGyroJerkMean  

### From the README of the original data set

Notes: 

- Features are normalized and bounded within [-1,1].

### Variables from the output data

 [1] "Activity"                         
 [2] "Subject"                          
 [3] "tBodyAcc.Mean.X"                  
 [4] "tBodyAcc.Mean.Y"                  
 [5] "tBodyAcc.Mean.Z"                  
 [6] "tBodyAcc.STD.X"                   
 [7] "tBodyAcc.STD.Y"                   
 [8] "tBodyAcc.STD.Z"                   
 [9] "tGravityAcc.Mean.X"               
[10] "tGravityAcc.Mean.Y"               
[11] "tGravityAcc.Mean.Z"               
[12] "tGravityAcc.STD.X"                
[13] "tGravityAcc.STD.Y"                
[14] "tGravityAcc.STD.Z"                
[15] "tBodyAccJerk.Mean.X"              
[16] "tBodyAccJerk.Mean.Y"              
[17] "tBodyAccJerk.Mean.Z"              
[18] "tBodyAccJerk.STD.X"               
[19] "tBodyAccJerk.STD.Y"               
[20] "tBodyAccJerk.STD.Z"               
[21] "tBodyGyro.Mean.X"                 
[22] "tBodyGyro.Mean.Y"                 
[23] "tBodyGyro.Mean.Z"                 
[24] "tBodyGyro.STD.X"                  
[25] "tBodyGyro.STD.Y"                  
[26] "tBodyGyro.STD.Z"                  
[27] "tBodyGyroJerk.Mean.X"             
[28] "tBodyGyroJerk.Mean.Y"             
[29] "tBodyGyroJerk.Mean.Z"             
[30] "tBodyGyroJerk.STD.X"              
[31] "tBodyGyroJerk.STD.Y"              
[32] "tBodyGyroJerk.STD.Z"              
[33] "tBodyAccMag.Mean."                
[34] "tBodyAccMag.STD."                 
[35] "tGravityAccMag.Mean."             
[36] "tGravityAccMag.STD."              
[37] "tBodyAccJerkMag.Mean."            
[38] "tBodyAccJerkMag.STD."             
[39] "tBodyGyroMag.Mean."               
[40] "tBodyGyroMag.STD."                
[41] "tBodyGyroJerkMag.Mean."           
[42] "tBodyGyroJerkMag.STD."            
[43] "fBodyAcc.Mean.X"                  
[44] "fBodyAcc.Mean.Y"                  
[45] "fBodyAcc.Mean.Z"                  
[46] "fBodyAcc.STD.X"                   
[47] "fBodyAcc.STD.Y"                   
[48] "fBodyAcc.STD.Z"                   
[49] "fBodyAccJerk.Mean.X"              
[50] "fBodyAccJerk.Mean.Y"              
[51] "fBodyAccJerk.Mean.Z"              
[52] "fBodyAccJerk.STD.X"               
[53] "fBodyAccJerk.STD.Y"               
[54] "fBodyAccJerk.STD.Z"               
[55] "fBodyGyro.Mean.X"                 
[56] "fBodyGyro.Mean.Y"                 
[57] "fBodyGyro.Mean.Z"                 
[58] "fBodyGyro.STD.X"                  
[59] "fBodyGyro.STD.Y"                  
[60] "fBodyGyro.STD.Z"                  
[61] "fBodyAccMag.Mean."                
[62] "fBodyAccMag.STD."                 
[63] "fBodyBodyAccJerkMag.Mean."        
[64] "fBodyBodyAccJerkMag.STD."         
[65] "fBodyBodyGyroMag.Mean."           
[66] "fBodyBodyGyroMag.STD."            
[67] "fBodyBodyGyroJerkMag.Mean."       
[68] "fBodyBodyGyroJerkMag.STD."        
[69] "angletBodyAccMeangravity"         
[70] "angletBodyAccJerkMeangravityMean" 
[71] "angletBodyGyroMeangravityMean"    
[72] "angletBodyGyroJerkMeangravityMean"
[73] "angleXgravityMean"                
[74] "angleYgravityMean"                
[75] "angleZgravityMean"  


